# CPU vs GPU sweep

Goal:

- Run the same sweep, on the same split, on CPU and on GPU.
- Compare hyperparameter sweep time and cost per run.

## Environment

Install libraries.

In [1]:
%pip install -q -U ultralytics torch torchvision onnx onnxslim onnxruntime mlflow sagemaker-mlflow

WARNING: Ignoring invalid distribution ~orch (/opt/conda/lib/python3.12/site-packages)

WARNING: Ignoring invalid distribution ~orch (/opt/conda/lib/python3.12/site-packages)

WARNING: Ignoring invalid distribution ~orch (/opt/conda/lib/python3.12/site-packages)

Note: you may need to restart the kernel to use updated packages.

Inspect enironment.

In [2]:
import json
import os
import sys
import time
from pathlib import Path

import boto3
import matplotlib.pyplot as plt
import mlflow
import pandas as pd
import torch

from sagemaker.core.helper.session_helper import Session

ROOT = Path.cwd().parent
sys.path.insert(0, str(ROOT))

from notebook.code.tracking import tracking_uri

# define paths
RAW = ROOT / "data" / "raw"
PROCESSED = ROOT / "data" / "processed"
RUNS = ROOT / "runs"
MODELS = ROOT / "models"

# create dir
for d in (RAW, PROCESSED, RUNS, MODELS):
    d.mkdir(parents=True, exist_ok=True)

REGION = Session().boto_region_name

# get bucket
env_file = Path.home() / ".sagemaker-yolo.env"
if "BUCKET" not in os.environ and env_file.exists():
    for line in env_file.read_text().splitlines():
        key, _, val = line.partition("=")
        os.environ.setdefault(key.strip(), val.strip())

BUCKET = os.environ["BUCKET"]

# bucket keys
S3_RAW = f"s3://{BUCKET}/raw-data/"
S3_SPLIT = f"s3://{BUCKET}/notebook/split-data"
S3_MODELS = f"s3://{BUCKET}/notebook/models"

# get device info: gpu
HAS_GPU = torch.cuda.is_available()

# set tracking server
TRACKING_URI = tracking_uri()
mlflow.set_tracking_uri(TRACKING_URI)

# set experiment
EXPERIMENT = "yolo-plate-detection-cpu-vs-gpu"
experiment = mlflow.set_experiment(EXPERIMENT)

# get tracking server
server = boto3.client("sagemaker").describe_mlflow_tracking_server(
    TrackingServerName=TRACKING_URI.rsplit("/", 1)[-1]
)
UI_URL = server["TrackingServerUrl"]

# print environment
print("torch     ", torch.__version__)
print("cuda      ", HAS_GPU)
print("gpu       ", torch.cuda.get_device_name(0) if HAS_GPU else "-")
print("cpu count ", os.cpu_count())
print("bucket    ", BUCKET)
print("experiment", EXPERIMENT, f"(id {experiment.experiment_id})")
print(f"\nUI: {UI_URL}/#/experiments/{experiment.experiment_id}")

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml

sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml

torch      2.13.0+cu130
cuda       True
gpu        Tesla T4
cpu count  4
bucket     sagemaker-yolo-dev-up68ac
experiment yolo-plate-detection-cpu-vs-gpu (id 3)

UI: https://t-dwc5gdj0ow9o.ca-central-1.experiments.sagemaker.aws/#/experiments/3

Identify the instance. The type is recorded on every run, so the comparison can
say which hardware produced which number.

In [3]:
# Studio writes the space's resource config here
metadata_file = Path("/opt/ml/metadata/resource-metadata.json")
INSTANCE = "unknown"

if metadata_file.exists():
    meta = json.loads(metadata_file.read_text())
    INSTANCE = (
        meta.get("ResourceArn", "").split("/")[-1]
        if "InstanceType" not in meta
        else meta["InstanceType"]
    )
    space = meta.get("SpaceName")
    if space:
        try:
            described = boto3.client("sagemaker").describe_space(
                DomainId=meta["DomainId"], SpaceName=space
            )
            INSTANCE = (
                described["SpaceSettings"]["JupyterLabAppSettings"]
                ["DefaultResourceSpec"]["InstanceType"]
            )
        except Exception as exc:
            print(f"could not read instance type from the space: {exc}")

# passes to run in this session: a GPU box can do both, a CPU box only one
PASSES = [("cpu", "cpu"), ("gpu", 0)] if HAS_GPU else [("cpu", "cpu")]

print("instance  ", INSTANCE)
print("passes    ", [p[0] for p in PASSES])

if not HAS_GPU:
    print(
        "\nNo GPU here, so only the CPU pass runs. To collect the GPU numbers:"
        "\n  1. File > Shut Down all apps (or stop the JupyterLab app in the console)"
        "\n  2. set notebook_instance_type to a GPU type, e.g. ml.g4dn.xlarge"
        "\n  3. terraform apply, restart the app, and run this notebook again"
        "\nThe split is pulled from S3 on the second run, so both passes see"
        "\nexactly the same data."
    )

instance   ml.g4dn.xlarge
passes     ['cpu', 'gpu']

## Data

Train on the identical split.

In [4]:
from notebook.code.data_loader import build_split, verify_split, write_data_yaml
from notebook.code.s3_sync import download, list_objects, upload

# cap the split for a quick check; set to None for the real comparison
# LIMIT = 200
LIMIT = None

SPLIT_SEED = 0

# reuse the split if exists
existing = list_objects(S3_SPLIT)

if existing and LIMIT is None:
    print(f"reusing the split in {S3_SPLIT}/ ({len(existing)} objects)")
    print(download(S3_SPLIT, PROCESSED))
else:
    if existing:
        print(f"LIMIT={LIMIT} set, so rebuilding rather than reusing S3")
    print(download(S3_RAW, RAW))
    print(build_split(RAW, PROCESSED, val_fraction=0.2, limit=LIMIT, seed=SPLIT_SEED))
    print(upload(PROCESSED, S3_SPLIT, delete=True))

print(verify_split(PROCESSED))

names = (RAW / "classes.txt").read_text().split() if (RAW / "classes.txt").exists() else ["car_plate"]
data_yaml = write_data_yaml(ROOT / "configs" / "data.yaml", PROCESSED, names)

n_train = sum(len(list((PROCESSED / s / "images").iterdir())) for s in ("train",))
n_images = sum(len(list((PROCESSED / s / "images").iterdir())) for s in ("train", "val"))
print(f"\n{n_images} images")

reusing the split in s3://sagemaker-yolo-dev-up68ac/notebook/split-data/ (400 objects)

{'downloaded': 0, 'skipped': 400}
{'train': 160, 'val': 40}

200 images

## Define sweep

The same grid runs on both devices.

In [5]:
from itertools import product

from notebook.code.data_loader import build_train_cfg

# the axes to sweep; identical for both devices
SWEEP = {
    "epochs": (10,),
}

GRID = [dict(zip(SWEEP.keys(), values)) for values in product(*SWEEP.values())]

print(f"{len(GRID)} configs x {len(PASSES)} passes = {len(GRID) * len(PASSES)} runs")
for g in GRID:
    print(" ", g)

1 configs x 2 passes = 2 runs
  {'epochs': 10}

## Run sweep

- One MLflow run per config per device. 
- Run names carry the device.

In [6]:
from notebook.code.tracking import run_sweep

results = []

for tag, device in PASSES:
    base_cfg = build_train_cfg(
        device=device,
        # ultralytics forces 0 dataloader workers on CPU
        workers=(os.cpu_count() or 2) if device != "cpu" else 0,
    )
    base_cfg["project"] = str(ROOT / base_cfg["project"])

    grid = [
        {**g, "name": f"{tag}-{n_train}img-{base_cfg['imgsz']}px-"
                      + "-".join(f"{v}{k}" for k, v in g.items())}
        for g in GRID
    ]

    print(f"\n{'#' * 60}\n# {tag} pass on {INSTANCE}\n{'#' * 60}")

    passed = run_sweep(
        grid=grid,
        base_cfg=base_cfg,
        data_yaml=data_yaml,
        processed_dir=PROCESSED,
        raw_dir=RAW,
        experiment=EXPERIMENT,
        run_name=lambda cfg: cfg["name"],
    )

    # tag each run so the comparison can group by device and hardware
    for r in passed:
        r["pass"] = tag
        r["instance"] = INSTANCE
        if "run_id" in r:
            with mlflow.start_run(run_id=r["run_id"]):
                mlflow.set_tags({
                    "pass": tag,
                    "instance": INSTANCE,
                    "cpu_count": os.cpu_count(),
                    "gpu": torch.cuda.get_device_name(0) if device != "cpu" else "none",
                })

    results.extend(passed)

pd.DataFrame(results)

############################################################
# cpu pass on ml.g4dn.xlarge
############################################################

============================================================
[1/1] cpu-160img-640px-10epochs  {'epochs': 10, 'name': 'cpu-160img-640px-10epochs'}
============================================================

Ultralytics 8.4.120 🚀 Python-3.12.13 torch-2.13.0+cu130 CPU (Intel Xeon Platinum 8259CL CPU @ 2.50GHz)

engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/sagemaker-user/sagemaker-yolo/configs/data.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=10, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=cpu-160img-640px-10epochs, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/home/sagemaker-user/sagemaker-yolo/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/home/sagemaker-user/sagemaker-yolo/runs/cpu-160img-640px-10epochs, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=0, workspace=None

Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments

  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]

  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]

  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]

  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]

  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]

  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]

  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]

  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]

  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]

  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]

 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]

 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']

 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]

 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']

 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]

 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]

 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]

 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]

 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]

 23        [16, 19, 22]  1    241566  ultralytics.nn.modules.head.Detect           [1, 1, True, [64, 128, 256]]

YOLO26n summary: 260 layers, 2,504,190 parameters, 2,504,190 gradients, 5.9 GFLOPs

Transferred 606/708 items from pretrained weights

train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3355.4±1025.2 MB/s, size: 720.9 KB)

train: Scanning /home/sagemaker-user/sagemaker-yolo/data/processed/train/labels.cache... 160 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 160/160 37.3Mit/s 0.0s

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3276.5±646.4 MB/s, size: 920.2 KB)

val: Scanning /home/sagemaker-user/sagemaker-yolo/data/processed/val/labels.cache... 40 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 40/40 7.6Mit/s 0.0s

optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...

optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)

Plotting labels to /home/sagemaker-user/sagemaker-yolo/runs/cpu-160img-640px-10epochs/labels.jpg...

2026/08/14 00:17:05 INFO mlflow.bedrock: Enabled auto-tracing for Bedrock. Note that MLflow can only trace boto3 service clients that are created after this call. If you have already created one, please recreate the client by calling `boto3.client`.

2026/08/14 00:17:05 INFO mlflow.tracking.fluent: Autologging successfully enabled for boto3.

MLflow: logging run_id(5919ce8856b74698b1ebba0b9339ba47) to arn:aws:sagemaker:ca-central-1:099139718958:mlflow-tracking-server/sagemaker-yolo-dev

MLflow: disable with 'yolo settings mlflow=False'

Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to /home/sagemaker-user/sagemaker-yolo/runs/cpu-160img-640px-10epochs
Starting training for 10 epochs...

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       1/10         0G      1.376      12.55    0.00718          8        640: 0% ──────────── 0/20  3.9s

       1/10         0G      1.332      12.64   0.006024          8        640: 5% ╸─────────── 1/20 10.4s/it 7.0s<3:17

       1/10         0G      1.262      12.39   0.005753          8        640: 10% ━─────────── 2/20 5.8s/it 9.9s<1:44

       1/10         0G      1.132      12.05   0.005476          8        640: 15% ━╸────────── 3/20 4.5s/it 12.8s<1:17

       1/10         0G      1.144         12   0.005708          8        640: 20% ━━────────── 4/20 3.7s/it 15.5s<59.8s

       1/10         0G      1.075      11.85   0.005518          8        640: 25% ━━━───────── 5/20 3.3s/it 18.1s<49.8s

       1/10         0G      1.097      11.89     0.0055          8        640: 30% ━━━╸──────── 6/20 3.1s/it 20.9s<43.5s

       1/10         0G      1.103      11.86   0.005511          8        640: 35% ━━━━──────── 7/20 3.0s/it 23.6s<38.8s

       1/10         0G      1.097      11.72   0.005421         10        640: 40% ━━━━╸─────── 8/20 2.9s/it 26.3s<34.7s

       1/10         0G      1.042       11.6   0.005186          8        640: 45% ━━━━━─────── 9/20 2.8s/it 28.9s<31.0s

       1/10         0G      1.014      11.51   0.005081          8        640: 50% ━━━━━━────── 10/20 2.8s/it 31.7s<28.1s

       1/10         0G     0.9896      11.42   0.005056          8        640: 55% ━━━━━━╸───── 11/20 2.8s/it 34.5s<25.0s

       1/10         0G     0.9736      11.37   0.005023          8        640: 60% ━━━━━━━───── 12/20 2.8s/it 37.4s<22.6s

       1/10         0G     0.9694      11.33   0.005008          8        640: 65% ━━━━━━━╸──── 13/20 2.9s/it 40.3s<20.0s

       1/10         0G     0.9449      11.25   0.004983          8        640: 70% ━━━━━━━━──── 14/20 2.8s/it 43.1s<17.0s

       1/10         0G     0.9456      11.23   0.004953          8        640: 75% ━━━━━━━━━─── 15/20 2.8s/it 45.9s<14.2s

       1/10         0G     0.9282      11.15   0.004898          8        640: 80% ━━━━━━━━━╸── 16/20 2.8s/it 48.6s<11.1s

       1/10         0G     0.9158      11.09   0.004839          8        640: 85% ━━━━━━━━━━── 17/20 2.8s/it 51.3s<8.3s

       1/10         0G      0.912      11.01   0.004775          9        640: 90% ━━━━━━━━━━╸─ 18/20 2.8s/it 54.1s<5.5s

       1/10         0G     0.9126      10.96   0.004842          8        640: 95% ━━━━━━━━━━━─ 19/20 2.7s/it 56.7s<2.7s

       1/10         0G     0.9126      10.96   0.004842          8        640: 100% ━━━━━━━━━━━━ 20/20 2.8s/it 56.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 1/3 4.4s/it 1.3s<8.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.8s/it 2.8s<2.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3s/it 4.0s

                   all         40         43    0.00208      0.581      0.143     0.0969

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       2/10         0G      0.976      10.28   0.004142          8        640: 0% ──────────── 0/20  2.6s

       2/10         0G     0.8622      10.07    0.00434          8        640: 5% ╸─────────── 1/20 9.0s/it 5.3s<2:50

       2/10         0G     0.8586      9.874   0.004119          8        640: 10% ━─────────── 2/20 5.3s/it 8.0s<1:35

       2/10         0G     0.8389      9.765   0.004639          8        640: 15% ━╸────────── 3/20 4.2s/it 10.8s<1:11

       2/10         0G     0.8103      9.727   0.004325          8        640: 20% ━━────────── 4/20 3.6s/it 13.5s<57.6s

       2/10         0G     0.7654      9.621   0.004095          8        640: 25% ━━━───────── 5/20 3.3s/it 16.2s<49.0s

       2/10         0G     0.8234      9.687   0.004188          8        640: 30% ━━━╸──────── 6/20 3.1s/it 18.9s<43.1s

       2/10         0G     0.8364      9.677   0.004458          8        640: 35% ━━━━──────── 7/20 3.0s/it 21.6s<38.5s

       2/10         0G     0.8276      9.671   0.004445          8        640: 40% ━━━━╸─────── 8/20 2.9s/it 24.3s<34.3s

       2/10         0G     0.8464      9.688   0.004446          8        640: 45% ━━━━━─────── 9/20 2.9s/it 27.1s<31.5s

       2/10         0G     0.8572      9.687   0.004575          8        640: 50% ━━━━━━────── 10/20 2.8s/it 29.8s<28.1s

       2/10         0G       0.84       9.66   0.004478          8        640: 55% ━━━━━━╸───── 11/20 2.8s/it 32.6s<25.2s

       2/10         0G     0.8796      9.609   0.004701         10        640: 60% ━━━━━━━───── 12/20 2.8s/it 35.4s<22.4s

       2/10         0G     0.8991      9.586   0.004865          8        640: 65% ━━━━━━━╸──── 13/20 2.9s/it 38.5s<20.1s

       2/10         0G     0.8993      9.565   0.004872          8        640: 70% ━━━━━━━━──── 14/20 2.9s/it 41.3s<17.2s

       2/10         0G     0.9093      9.543   0.004999          8        640: 75% ━━━━━━━━━─── 15/20 2.8s/it 44.1s<14.1s

       2/10         0G     0.9218      9.518   0.005015          8        640: 80% ━━━━━━━━━╸── 16/20 2.8s/it 46.9s<11.3s

       2/10         0G     0.9254      9.523   0.005008          8        640: 85% ━━━━━━━━━━── 17/20 2.8s/it 49.6s<8.4s

       2/10         0G     0.9256      9.507   0.005005          8        640: 90% ━━━━━━━━━━╸─ 18/20 2.8s/it 52.4s<5.6s

       2/10         0G     0.9451      9.567   0.005058          7        640: 95% ━━━━━━━━━━━─ 19/20 2.8s/it 55.1s<2.8s

       2/10         0G     0.9451      9.567   0.005058          7        640: 100% ━━━━━━━━━━━━ 20/20 2.8s/it 55.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 1/3 4.2s/it 1.3s<8.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.7s/it 2.7s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3s/it 3.8s

                   all         40         43     0.0025      0.698      0.123     0.0821

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       3/10         0G      1.075      9.017   0.005785          8        640: 0% ──────────── 0/20  2.8s

       3/10         0G     0.9744      8.892   0.005037          8        640: 5% ╸─────────── 1/20 8.8s/it 5.5s<2:47

       3/10         0G     0.9436      8.788    0.00495          8        640: 10% ━─────────── 2/20 5.2s/it 8.2s<1:34

       3/10         0G     0.9585      8.843     0.0051          8        640: 15% ━╸────────── 3/20 4.1s/it 10.9s<1:09

       3/10         0G     0.9586      8.858   0.005426          8        640: 20% ━━────────── 4/20 3.6s/it 13.6s<57.1s

       3/10         0G     0.9204      8.723   0.005081          9        640: 25% ━━━───────── 5/20 3.4s/it 16.7s<51.1s

       3/10         0G     0.8992      8.676   0.005302          8        640: 30% ━━━╸──────── 6/20 3.3s/it 19.7s<45.8s

       3/10         0G     0.9238      8.715   0.005334          8        640: 35% ━━━━──────── 7/20 3.1s/it 22.4s<40.0s

       3/10         0G     0.9444      8.601   0.005267         10        640: 40% ━━━━╸─────── 8/20 3.1s/it 25.4s<36.9s

       3/10         0G     0.9475      8.654   0.005587          8        640: 45% ━━━━━─────── 9/20 3.0s/it 28.2s<32.5s

       3/10         0G     0.9402      8.648   0.005494          8        640: 50% ━━━━━━────── 10/20 2.9s/it 30.9s<28.9s

       3/10         0G     0.9433      8.664   0.005377          8        640: 55% ━━━━━━╸───── 11/20 2.8s/it 33.5s<25.2s

       3/10         0G      0.949      8.659   0.005354          8        640: 60% ━━━━━━━───── 12/20 2.8s/it 36.2s<22.2s

       3/10         0G     0.9648      8.674   0.005397          8        640: 65% ━━━━━━━╸──── 13/20 2.8s/it 39.1s<19.6s

       3/10         0G     0.9536      8.648   0.005352          8        640: 70% ━━━━━━━━──── 14/20 2.8s/it 41.9s<16.7s

       3/10         0G      0.944       8.63   0.005232          8        640: 75% ━━━━━━━━━─── 15/20 2.8s/it 44.6s<13.9s

       3/10         0G     0.9475      8.616   0.005234          8        640: 80% ━━━━━━━━━╸── 16/20 2.8s/it 47.5s<11.3s

       3/10         0G     0.9477      8.591   0.005305          8        640: 85% ━━━━━━━━━━── 17/20 2.8s/it 50.2s<8.3s

       3/10         0G     0.9395       8.57    0.00527          8        640: 90% ━━━━━━━━━━╸─ 18/20 2.8s/it 53.0s<5.5s

       3/10         0G     0.9465      8.582   0.005263          8        640: 95% ━━━━━━━━━━━─ 19/20 2.7s/it 55.6s<2.7s

       3/10         0G     0.9465      8.582   0.005263          8        640: 100% ━━━━━━━━━━━━ 20/20 2.8s/it 55.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 1/3 4.2s/it 1.3s<8.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.7s/it 2.8s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3s/it 3.8s

                   all         40         43    0.00267      0.744     0.0655     0.0474

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       4/10         0G      1.186      8.772   0.005805          8        640: 0% ──────────── 0/20  2.7s

       4/10         0G      1.076      8.487   0.005599          8        640: 5% ╸─────────── 1/20 8.9s/it 5.4s<2:50

       4/10         0G     0.9903      8.362    0.00494          8        640: 10% ━─────────── 2/20 5.2s/it 8.0s<1:34

       4/10         0G     0.9865      8.312   0.005065          8        640: 15% ━╸────────── 3/20 4.1s/it 10.7s<1:09

       4/10         0G     0.9647      8.251   0.005036          8        640: 20% ━━────────── 4/20 3.5s/it 13.3s<55.8s

       4/10         0G     0.9805      8.265   0.005196          8        640: 25% ━━━───────── 5/20 3.3s/it 16.2s<48.8s

       4/10         0G     0.9876      8.237   0.005357          8        640: 30% ━━━╸──────── 6/20 3.1s/it 18.9s<42.9s

       4/10         0G      1.004       8.16   0.005215          9        640: 35% ━━━━──────── 7/20 3.0s/it 21.6s<38.5s

       4/10         0G       1.01      8.205   0.005231          8        640: 40% ━━━━╸─────── 8/20 2.9s/it 24.3s<34.7s

       4/10         0G      1.022      8.253   0.005576          8        640: 45% ━━━━━─────── 9/20 2.9s/it 27.2s<31.7s

       4/10         0G      1.005      8.274    0.00559          8        640: 50% ━━━━━━────── 10/20 2.9s/it 30.0s<28.6s

       4/10         0G     0.9931      8.235   0.005695          8        640: 55% ━━━━━━╸───── 11/20 2.9s/it 32.9s<25.7s

       4/10         0G       1.02      8.228   0.005595          8        640: 60% ━━━━━━━───── 12/20 2.8s/it 35.6s<22.6s

       4/10         0G      1.019      8.212   0.005606          8        640: 65% ━━━━━━━╸──── 13/20 2.8s/it 38.3s<19.5s

       4/10         0G      1.005      8.187   0.005646          8        640: 70% ━━━━━━━━──── 14/20 2.8s/it 41.1s<16.7s

       4/10         0G      1.008      8.178    0.00566          8        640: 75% ━━━━━━━━━─── 15/20 2.8s/it 43.8s<13.8s

       4/10         0G      1.003      8.137   0.005655          8        640: 80% ━━━━━━━━━╸── 16/20 2.8s/it 46.6s<11.1s

       4/10         0G     0.9964      8.155   0.005702          8        640: 85% ━━━━━━━━━━── 17/20 2.8s/it 49.4s<8.3s

       4/10         0G          1      8.109   0.005714         10        640: 90% ━━━━━━━━━━╸─ 18/20 2.8s/it 52.2s<5.6s

       4/10         0G      0.995      8.083   0.005797          8        640: 95% ━━━━━━━━━━━─ 19/20 2.7s/it 54.8s<2.7s

       4/10         0G      0.995      8.083   0.005797          8        640: 100% ━━━━━━━━━━━━ 20/20 2.7s/it 54.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 1/3 4.4s/it 1.3s<8.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.8s/it 2.9s<2.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3s/it 4.0s

                   all         40         43      0.852      0.135      0.582      0.442

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       5/10         0G     0.9113      8.024   0.006662          8        640: 0% ──────────── 0/20  2.7s

       5/10         0G     0.8711      7.879   0.006679          8        640: 5% ╸─────────── 1/20 9.0s/it 5.4s<2:51

       5/10         0G     0.8822      7.794   0.006247          8        640: 10% ━─────────── 2/20 5.2s/it 8.0s<1:33

       5/10         0G     0.9291      7.865   0.006265          8        640: 15% ━╸────────── 3/20 4.1s/it 10.7s<1:10

       5/10         0G     0.8987      7.824   0.006388          8        640: 20% ━━────────── 4/20 3.6s/it 13.5s<57.1s

       5/10         0G      0.902      7.779   0.006185          8        640: 25% ━━━───────── 5/20 3.3s/it 16.3s<49.6s

       5/10         0G     0.9586      7.807   0.006654          8        640: 30% ━━━╸──────── 6/20 3.1s/it 19.1s<43.6s

       5/10         0G     0.9873      7.828   0.007117          8        640: 35% ━━━━──────── 7/20 3.0s/it 21.8s<38.9s

       5/10         0G      1.004      7.935   0.007508          7        640: 40% ━━━━╸─────── 8/20 3.0s/it 24.8s<36.0s

       5/10         0G      1.019      7.926   0.007316          8        640: 45% ━━━━━─────── 9/20 2.9s/it 27.5s<31.9s

       5/10         0G      1.017      7.896   0.007313          8        640: 50% ━━━━━━────── 10/20 2.8s/it 30.2s<28.4s

       5/10         0G      1.038      7.876   0.007429          8        640: 55% ━━━━━━╸───── 11/20 2.8s/it 33.0s<25.5s

       5/10         0G      1.057      7.873   0.007697          8        640: 60% ━━━━━━━───── 12/20 2.8s/it 35.7s<22.4s

       5/10         0G      1.064      7.863   0.007547          8        640: 65% ━━━━━━━╸──── 13/20 2.8s/it 38.6s<19.7s

       5/10         0G      1.066      7.814   0.007468          8        640: 70% ━━━━━━━━──── 14/20 2.8s/it 41.2s<16.6s

       5/10         0G      1.084      7.732   0.007616         10        640: 75% ━━━━━━━━━─── 15/20 2.8s/it 44.0s<13.9s

       5/10         0G      1.105       7.69   0.007487          9        640: 80% ━━━━━━━━━╸── 16/20 2.8s/it 47.0s<11.3s

       5/10         0G      1.116      7.715   0.007496          8        640: 85% ━━━━━━━━━━── 17/20 2.8s/it 49.8s<8.4s

       5/10         0G      1.127      7.707   0.007502          8        640: 90% ━━━━━━━━━━╸─ 18/20 2.8s/it 52.5s<5.6s

       5/10         0G      1.145      7.683   0.007519          9        640: 95% ━━━━━━━━━━━─ 19/20 2.8s/it 55.3s<2.8s

       5/10         0G      1.145      7.683   0.007519          9        640: 100% ━━━━━━━━━━━━ 20/20 2.8s/it 55.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 1/3 4.3s/it 1.3s<8.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.9s/it 2.9s<2.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3s/it 4.0s

                   all         40         43      0.743      0.471      0.666      0.513

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       6/10         0G      1.175      7.203    0.01065          8        640: 0% ──────────── 0/20  2.6s

       6/10         0G      1.461      7.719   0.008668          8        640: 5% ╸─────────── 1/20 9.2s/it 5.3s<2:54

       6/10         0G      1.434       7.62   0.007771          8        640: 10% ━─────────── 2/20 5.2s/it 7.9s<1:34

       6/10         0G      1.291      7.417   0.006968          8        640: 15% ━╸────────── 3/20 4.1s/it 10.7s<1:10

       6/10         0G      1.228      7.375   0.007039          8        640: 20% ━━────────── 4/20 3.7s/it 13.6s<58.5s

       6/10         0G      1.227      7.446   0.007974          8        640: 25% ━━━───────── 5/20 3.3s/it 16.3s<49.5s

       6/10         0G      1.199      7.415   0.007866          8        640: 30% ━━━╸──────── 6/20 3.2s/it 19.3s<44.8s

       6/10         0G      1.169      7.372   0.007323          8        640: 35% ━━━━──────── 7/20 3.0s/it 22.0s<39.4s

       6/10         0G      1.147      7.337   0.007037          8        640: 40% ━━━━╸─────── 8/20 2.9s/it 24.7s<35.1s

       6/10         0G      1.127      7.325   0.006994          8        640: 45% ━━━━━─────── 9/20 2.9s/it 27.4s<31.4s

       6/10         0G       1.13      7.218   0.006742          9        640: 50% ━━━━━━────── 10/20 2.8s/it 30.1s<28.3s

       6/10         0G      1.147      7.251   0.006941          8        640: 55% ━━━━━━╸───── 11/20 2.8s/it 32.9s<25.2s

       6/10         0G      1.126      7.216   0.006831          8        640: 60% ━━━━━━━───── 12/20 2.7s/it 35.5s<21.9s

       6/10         0G      1.102        7.2     0.0067          8        640: 65% ━━━━━━━╸──── 13/20 2.7s/it 38.1s<18.9s

       6/10         0G      1.095      7.101   0.006563         10        640: 70% ━━━━━━━━──── 14/20 2.7s/it 41.0s<16.5s

       6/10         0G      1.091      7.081   0.006626          8        640: 75% ━━━━━━━━━─── 15/20 2.7s/it 43.7s<13.7s

       6/10         0G      1.081      7.058   0.006497          8        640: 80% ━━━━━━━━━╸── 16/20 2.8s/it 46.5s<11.0s

       6/10         0G      1.093      7.041   0.006377          9        640: 85% ━━━━━━━━━━── 17/20 2.8s/it 49.3s<8.4s

       6/10         0G      1.091      7.035   0.006353          8        640: 90% ━━━━━━━━━━╸─ 18/20 2.8s/it 52.2s<5.6s

       6/10         0G      1.084      7.016   0.006278          8        640: 95% ━━━━━━━━━━━─ 19/20 2.8s/it 55.0s<2.8s

       6/10         0G      1.084      7.016   0.006278          8        640: 100% ━━━━━━━━━━━━ 20/20 2.7s/it 55.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 1/3 4.2s/it 1.3s<8.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.7s/it 2.7s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3s/it 3.9s

                   all         40         43      0.661      0.544      0.674      0.489

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       7/10         0G     0.9092      6.973    0.00533          8        640: 0% ──────────── 0/20  2.6s

       7/10         0G      1.068       7.12   0.006247          8        640: 5% ╸─────────── 1/20 9.2s/it 5.3s<2:55

       7/10         0G      1.059      7.026   0.006293          8        640: 10% ━─────────── 2/20 5.3s/it 8.0s<1:35

       7/10         0G     0.9837       6.95   0.006238          8        640: 15% ━╸────────── 3/20 4.1s/it 10.7s<1:10

       7/10         0G      1.053      6.949    0.00639          8        640: 20% ━━────────── 4/20 3.6s/it 13.5s<58.1s

       7/10         0G      1.027      6.916   0.006313          8        640: 25% ━━━───────── 5/20 3.3s/it 16.2s<49.3s

       7/10         0G      1.036      6.852   0.006068          8        640: 30% ━━━╸──────── 6/20 3.1s/it 18.8s<42.7s

       7/10         0G      1.064      6.859   0.006253          8        640: 35% ━━━━──────── 7/20 3.0s/it 21.6s<38.4s

       7/10         0G      1.056      6.817   0.006194          8        640: 40% ━━━━╸─────── 8/20 2.9s/it 24.3s<34.4s

       7/10         0G      1.059       6.83   0.006359          8        640: 45% ━━━━━─────── 9/20 2.8s/it 27.0s<30.9s

       7/10         0G       1.08      6.767   0.006255         10        640: 50% ━━━━━━────── 10/20 2.8s/it 29.7s<28.0s

       7/10         0G      1.076      6.783    0.00619          8        640: 55% ━━━━━━╸───── 11/20 2.8s/it 32.5s<25.1s

       7/10         0G      1.081       6.81    0.00631          8        640: 60% ━━━━━━━───── 12/20 2.8s/it 35.2s<22.0s

       7/10         0G      1.072      6.789   0.006196          8        640: 65% ━━━━━━━╸──── 13/20 2.8s/it 38.2s<19.8s

       7/10         0G      1.061      6.765   0.006045          8        640: 70% ━━━━━━━━──── 14/20 2.8s/it 40.9s<16.7s

       7/10         0G      1.048      6.745   0.006073          8        640: 75% ━━━━━━━━━─── 15/20 2.8s/it 43.7s<13.9s

       7/10         0G      1.028      6.729   0.005915          8        640: 80% ━━━━━━━━━╸── 16/20 2.8s/it 46.5s<11.2s

       7/10         0G      1.032      6.738   0.005897          8        640: 85% ━━━━━━━━━━── 17/20 2.8s/it 49.3s<8.4s

       7/10         0G      1.023      6.725   0.005818          8        640: 90% ━━━━━━━━━━╸─ 18/20 2.8s/it 52.0s<5.6s

       7/10         0G      1.022      6.719   0.005862          8        640: 95% ━━━━━━━━━━━─ 19/20 2.8s/it 55.0s<2.8s

       7/10         0G      1.022      6.719   0.005862          8        640: 100% ━━━━━━━━━━━━ 20/20 2.7s/it 55.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 1/3 4.3s/it 1.3s<8.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.7s/it 2.8s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3s/it 3.9s

                   all         40         43      0.657      0.581      0.694       0.54

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       8/10         0G     0.7365       6.86   0.006338          8        640: 0% ──────────── 0/20  2.8s

       8/10         0G     0.8294      6.626   0.004917          8        640: 5% ╸─────────── 1/20 9.3s/it 5.6s<2:57

       8/10         0G     0.7695      6.473   0.004308          8        640: 10% ━─────────── 2/20 5.3s/it 8.3s<1:36

       8/10         0G     0.8096      6.457   0.004374          8        640: 15% ━╸────────── 3/20 4.2s/it 11.1s<1:11

       8/10         0G     0.8581      6.381   0.004298          9        640: 20% ━━────────── 4/20 3.6s/it 13.8s<57.9s

       8/10         0G     0.9145      6.464   0.005015          8        640: 25% ━━━───────── 5/20 3.3s/it 16.5s<49.4s

       8/10         0G     0.9515      6.457   0.005064          8        640: 30% ━━━╸──────── 6/20 3.2s/it 19.4s<44.1s

       8/10         0G      0.946      6.458   0.004883          8        640: 35% ━━━━──────── 7/20 3.0s/it 22.1s<39.2s

       8/10         0G     0.9384      6.431   0.004764          8        640: 40% ━━━━╸─────── 8/20 2.9s/it 24.8s<34.9s

       8/10         0G      0.925      6.435   0.004725          8        640: 45% ━━━━━─────── 9/20 2.9s/it 27.6s<31.5s

       8/10         0G      0.939       6.44   0.004673          8        640: 50% ━━━━━━────── 10/20 2.8s/it 30.2s<27.9s

       8/10         0G     0.9594      6.382   0.004651         10        640: 55% ━━━━━━╸───── 11/20 2.8s/it 32.9s<24.9s

       8/10         0G     0.9739      6.403    0.00472          8        640: 60% ━━━━━━━───── 12/20 2.8s/it 35.7s<22.2s

       8/10         0G     0.9606      6.404   0.004888          8        640: 65% ━━━━━━━╸──── 13/20 2.8s/it 38.5s<19.4s

       8/10         0G     0.9421      6.388   0.004894          8        640: 70% ━━━━━━━━──── 14/20 2.8s/it 41.2s<16.6s

       8/10         0G     0.9542      6.388   0.005104          8        640: 75% ━━━━━━━━━─── 15/20 2.8s/it 44.0s<13.8s

       8/10         0G     0.9406      6.405   0.005278          8        640: 80% ━━━━━━━━━╸── 16/20 2.7s/it 46.6s<10.8s

       8/10         0G     0.9318      6.378   0.005182          8        640: 85% ━━━━━━━━━━── 17/20 2.7s/it 49.3s<8.1s

       8/10         0G     0.9234      6.363   0.005306          8        640: 90% ━━━━━━━━━━╸─ 18/20 2.7s/it 52.0s<5.4s

       8/10         0G     0.9352      6.379   0.005373          8        640: 95% ━━━━━━━━━━━─ 19/20 2.7s/it 54.7s<2.7s

       8/10         0G     0.9352      6.379   0.005373          8        640: 100% ━━━━━━━━━━━━ 20/20 2.7s/it 54.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 1/3 4.3s/it 1.3s<8.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.8s/it 2.8s<2.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3s/it 3.9s

                   all         40         43      0.735      0.721      0.743       0.59

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       9/10         0G     0.7884      5.967   0.004783          8        640: 0% ──────────── 0/20  2.8s

       9/10         0G     0.7519      5.935   0.004419          8        640: 5% ╸─────────── 1/20 8.9s/it 5.5s<2:49

       9/10         0G     0.7553      5.997   0.004812          8        640: 10% ━─────────── 2/20 5.2s/it 8.2s<1:34

       9/10         0G     0.8099      6.075   0.004563          8        640: 15% ━╸────────── 3/20 4.2s/it 11.0s<1:11

       9/10         0G     0.8764      6.061   0.004576          9        640: 20% ━━────────── 4/20 3.6s/it 13.8s<57.9s

       9/10         0G     0.8391       6.09    0.00441          8        640: 25% ━━━───────── 5/20 3.3s/it 16.6s<50.2s

       9/10         0G     0.8363      6.094   0.004286          8        640: 30% ━━━╸──────── 6/20 3.1s/it 19.2s<42.9s

       9/10         0G     0.8552      6.108   0.004406          8        640: 35% ━━━━──────── 7/20 3.0s/it 22.0s<38.7s

       9/10         0G     0.8924      6.139   0.004499          8        640: 40% ━━━━╸─────── 8/20 2.9s/it 24.7s<34.8s

       9/10         0G     0.9044      6.139   0.004727          8        640: 45% ━━━━━─────── 9/20 2.9s/it 27.5s<31.7s

       9/10         0G     0.9192      6.145   0.004749          8        640: 50% ━━━━━━────── 10/20 2.9s/it 30.4s<28.8s

       9/10         0G     0.9265       6.16   0.004776          8        640: 55% ━━━━━━╸───── 11/20 2.9s/it 33.2s<25.7s

       9/10         0G     0.9199      6.121   0.004718          8        640: 60% ━━━━━━━───── 12/20 2.8s/it 35.9s<22.4s

       9/10         0G     0.9081      6.096   0.004704          8        640: 65% ━━━━━━━╸──── 13/20 2.8s/it 38.7s<19.7s

       9/10         0G     0.9138      6.043   0.004691         10        640: 70% ━━━━━━━━──── 14/20 2.7s/it 41.3s<16.4s

       9/10         0G     0.9258      6.097   0.004643          8        640: 75% ━━━━━━━━━─── 15/20 2.7s/it 44.0s<13.6s

       9/10         0G     0.9244      6.106   0.004633          8        640: 80% ━━━━━━━━━╸── 16/20 2.7s/it 46.7s<10.8s

       9/10         0G     0.9315      6.121   0.004646          8        640: 85% ━━━━━━━━━━── 17/20 2.8s/it 49.5s<8.3s

       9/10         0G     0.9374       6.13   0.004589          8        640: 90% ━━━━━━━━━━╸─ 18/20 2.7s/it 52.2s<5.5s

       9/10         0G     0.9301      6.095   0.004537          9        640: 95% ━━━━━━━━━━━─ 19/20 2.7s/it 54.9s<2.7s

       9/10         0G     0.9301      6.095   0.004537          9        640: 100% ━━━━━━━━━━━━ 20/20 2.7s/it 54.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 1/3 4.2s/it 1.3s<8.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.7s/it 2.7s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3s/it 3.8s

                   all         40         43      0.761      0.674      0.761      0.593

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

      10/10         0G     0.9632      6.064   0.004813          8        640: 0% ──────────── 0/20  2.6s

      10/10         0G     0.8975      5.972   0.004327          8        640: 5% ╸─────────── 1/20 9.6s/it 5.5s<3:02

      10/10         0G     0.9269      5.885   0.003989          9        640: 10% ━─────────── 2/20 5.6s/it 8.3s<1:40

      10/10         0G     0.8992      5.883   0.004242          8        640: 15% ━╸────────── 3/20 4.2s/it 11.0s<1:12

      10/10         0G     0.8772      5.886   0.004285          8        640: 20% ━━────────── 4/20 3.6s/it 13.6s<57.0s

      10/10         0G     0.8489      5.826    0.00414          8        640: 25% ━━━───────── 5/20 3.2s/it 16.3s<48.6s

      10/10         0G      0.849      5.812   0.004414          8        640: 30% ━━━╸──────── 6/20 3.1s/it 19.0s<43.1s

      10/10         0G     0.8929      5.878   0.004385          8        640: 35% ━━━━──────── 7/20 2.9s/it 21.7s<38.0s

      10/10         0G      0.894      5.867   0.004387          8        640: 40% ━━━━╸─────── 8/20 2.8s/it 24.3s<34.1s

      10/10         0G     0.8914      5.894   0.004564          8        640: 45% ━━━━━─────── 9/20 2.8s/it 27.0s<30.8s

      10/10         0G     0.9013      5.901   0.004536          8        640: 50% ━━━━━━────── 10/20 2.8s/it 29.8s<27.8s

      10/10         0G     0.8659      5.876   0.004347          8        640: 55% ━━━━━━╸───── 11/20 2.8s/it 32.5s<24.9s

      10/10         0G     0.8728      5.891   0.004536          8        640: 60% ━━━━━━━───── 12/20 2.7s/it 35.2s<22.0s

      10/10         0G     0.8636      5.896   0.004575          8        640: 65% ━━━━━━━╸──── 13/20 2.8s/it 38.1s<19.5s

      10/10         0G     0.8752      5.863   0.004533         10        640: 70% ━━━━━━━━──── 14/20 2.8s/it 40.9s<16.7s

      10/10         0G     0.9158      5.934   0.004572          8        640: 75% ━━━━━━━━━─── 15/20 2.8s/it 43.6s<13.8s

      10/10         0G     0.9099      5.939   0.004551          8        640: 80% ━━━━━━━━━╸── 16/20 2.7s/it 46.3s<11.0s

      10/10         0G     0.9426      5.951   0.004524          9        640: 85% ━━━━━━━━━━── 17/20 2.8s/it 49.2s<8.4s

      10/10         0G     0.9322      5.951   0.004457          8        640: 90% ━━━━━━━━━━╸─ 18/20 2.8s/it 52.0s<5.6s

      10/10         0G     0.9252      5.955   0.004367          8        640: 95% ━━━━━━━━━━━─ 19/20 2.8s/it 54.8s<2.8s

      10/10         0G     0.9252      5.955   0.004367          8        640: 100% ━━━━━━━━━━━━ 20/20 2.7s/it 54.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 1/3 4.4s/it 1.3s<8.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.9s/it 3.0s<2.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.4s/it 4.1s

                   all         40         43       0.79      0.674       0.78      0.612

10 epochs completed in 0.167 hours.

Optimizer stripped from /home/sagemaker-user/sagemaker-yolo/runs/cpu-160img-640px-10epochs/weights/last.pt, 5.4MB

Optimizer stripped from /home/sagemaker-user/sagemaker-yolo/runs/cpu-160img-640px-10epochs/weights/best.pt, 5.4MB

Validating /home/sagemaker-user/sagemaker-yolo/runs/cpu-160img-640px-10epochs/weights/best.pt...

Ultralytics 8.4.120 🚀 Python-3.12.13 torch-2.13.0+cu130 CPU (Intel Xeon Platinum 8259CL CPU @ 2.50GHz)

YOLO26n summary (fused): 122 layers, 2,375,031 parameters, 0 gradients, 5.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 1/3 3.4s/it 1.0s<6.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.3s/it 2.4s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1s/it 3.4s

                   all         40         43       0.79      0.674       0.78      0.612

Speed: 0.9ms preprocess, 60.0ms inference, 0.0ms loss, 0.1ms postprocess per image

Results saved to /home/sagemaker-user/sagemaker-yolo/runs/cpu-160img-640px-10epochs

MLflow: results logged to arn:aws:sagemaker:ca-central-1:099139718958:mlflow-tracking-server/sagemaker-yolo-dev
MLflow: disable with 'yolo settings mlflow=False'

MLflow: mlflow run still alive, remember to close it using mlflow.end_run()

🏃 View run cpu-160img-640px-10epochs at: https://ca-central-1.experiments.sagemaker.aws/#/experiments/3/runs/5919ce8856b74698b1ebba0b9339ba47
🧪 View experiment at: https://ca-central-1.experiments.sagemaker.aws/#/experiments/3
[1/1] done in 613s

🏃 View run cpu-160img-640px-10epochs at: https://ca-central-1.experiments.sagemaker.aws/#/experiments/3/runs/5919ce8856b74698b1ebba0b9339ba47
🧪 View experiment at: https://ca-central-1.experiments.sagemaker.aws/#/experiments/3

############################################################
# gpu pass on ml.g4dn.xlarge
############################################################

============================================================
[1/1] gpu-160img-640px-10epochs  {'epochs': 10, 'name': 'gpu-160img-640px-10epochs'}
============================================================

Ultralytics 8.4.120 🚀 Python-3.12.13 torch-2.13.0+cu130 CUDA:0 (Tesla T4, 14913MiB)

engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/sagemaker-user/sagemaker-yolo/configs/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=10, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=gpu-160img-640px-10epochs, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/home/sagemaker-user/sagemaker-yolo/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/home/sagemaker-user/sagemaker-yolo/runs/gpu-160img-640px-10epochs, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None

Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments

  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]

  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]

  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]

  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]

  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]

  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]

  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]

  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]

  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]

  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]

 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]

 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']

 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]

 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']

 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]

 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]

 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]

 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]

 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]

 23        [16, 19, 22]  1    241566  ultralytics.nn.modules.head.Detect           [1, 1, True, [64, 128, 256]]

YOLO26n summary: 260 layers, 2,504,190 parameters, 2,504,190 gradients, 5.9 GFLOPs

Transferred 606/708 items from pretrained weights

AMP: running Automatic Mixed Precision (AMP) checks...

AMP: checks passed ✅

train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3353.1±987.9 MB/s, size: 410.1 KB)

train: Scanning /home/sagemaker-user/sagemaker-yolo/data/processed/train/labels.cache... 160 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 160/160 67.1Mit/s 0.0s

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1366.4±790.3 MB/s, size: 929.1 KB)

val: Scanning /home/sagemaker-user/sagemaker-yolo/data/processed/val/labels.cache... 40 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 40/40 2.9Mit/s 0.0s

optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...

optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)

Plotting labels to /home/sagemaker-user/sagemaker-yolo/runs/gpu-160img-640px-10epochs/labels.jpg...

2026/08/14 00:27:20 INFO mlflow.bedrock: Enabled auto-tracing for Bedrock. Note that MLflow can only trace boto3 service clients that are created after this call. If you have already created one, please recreate the client by calling `boto3.client`.

2026/08/14 00:27:20 INFO mlflow.tracking.fluent: Autologging successfully enabled for boto3.

MLflow: logging run_id(8843e42655bc431bbf79df04b2f08e0b) to arn:aws:sagemaker:ca-central-1:099139718958:mlflow-tracking-server/sagemaker-yolo-dev

MLflow: disable with 'yolo settings mlflow=False'

Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /home/sagemaker-user/sagemaker-yolo/runs/gpu-160img-640px-10epochs
Starting training for 10 epochs...

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       1/10      1.22G     0.9784      11.76   0.005388          8        640: 0% ──────────── 0/20  6.1s

       1/10      1.22G       1.17      12.01   0.006558          8        640: 5% ╸─────────── 1/20 1.9it/s 6.3s<10.2s

       1/10      1.23G      1.173      11.47   0.005913         10        640: 10% ━─────────── 2/20 2.7it/s 6.5s<6.7s

       1/10      1.23G      1.117      11.57   0.005661          8        640: 15% ━╸────────── 3/20 2.8it/s 6.8s<6.1s

       1/10      1.24G      1.086      11.58   0.005779          8        640: 20% ━━────────── 4/20 4.1it/s 7.0s<3.9s

       1/10      1.24G       1.13      11.68   0.006368          8        640: 25% ━━━───────── 5/20 5.6it/s 7.1s<2.7s

       1/10      1.25G        1.1      11.69   0.006109          8        640: 30% ━━━╸──────── 6/20 5.9it/s 7.2s<2.4s

       1/10      1.25G       1.08      11.68   0.006069          8        640: 35% ━━━━──────── 7/20 6.2it/s 7.4s<2.1s

       1/10      1.25G      1.101      11.75   0.006089          8        640: 40% ━━━━╸─────── 8/20 6.0it/s 7.5s<2.0s

       1/10      1.25G      1.081       11.7   0.006117          8        640: 45% ━━━━━─────── 9/20 6.7it/s 7.7s<1.6s

       1/10      1.25G      1.099      11.69   0.006088          9        640: 50% ━━━━━━────── 10/20 6.5it/s 7.8s<1.5s

       1/10      1.25G      1.082      11.68   0.005858          8        640: 55% ━━━━━━╸───── 11/20 6.6it/s 8.0s<1.4s

       1/10      1.25G      1.042      11.61   0.005625          8        640: 60% ━━━━━━━───── 12/20 6.4it/s 8.1s<1.3s

       1/10      1.25G      1.022      11.54   0.005514          8        640: 65% ━━━━━━━╸──── 13/20 7.0it/s 8.3s<1.0s

       1/10      1.25G      1.016      11.51   0.005462          8        640: 70% ━━━━━━━━──── 14/20 7.1it/s 8.4s<0.8s

       1/10      1.25G     0.9994      11.46   0.005377          8        640: 75% ━━━━━━━━━─── 15/20 6.7it/s 8.6s<0.7s

       1/10      1.25G     0.9928      11.38   0.005272          9        640: 80% ━━━━━━━━━╸── 16/20 7.0it/s 8.7s<0.6s

       1/10      1.25G     0.9753      11.33   0.005232          8        640: 85% ━━━━━━━━━━── 17/20 7.0it/s 8.8s<0.4s

       1/10      1.25G     0.9554      11.27   0.005139          8        640: 90% ━━━━━━━━━━╸─ 18/20 6.9it/s 9.0s<0.3s

       1/10      1.25G     0.9479      11.21   0.005169          8        640: 95% ━━━━━━━━━━━─ 19/20 7.3it/s 9.1s<0.1s

       1/10      1.25G     0.9479      11.21   0.005169          8        640: 100% ━━━━━━━━━━━━ 20/20 2.2it/s 9.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 1/3 4.9s/it 1.5s<9.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.7s/it 2.8s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.4s/it 4.3s

                   all         40         43    0.00183      0.512      0.108     0.0807

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       2/10      1.46G     0.8614       10.2   0.005783          8        640: 0% ──────────── 0/20  0.1s

       2/10      1.46G     0.7464      10.18   0.004067          8        640: 5% ╸─────────── 1/20 1.6it/s 0.3s<11.8s

       2/10      1.46G      0.833      9.956   0.004217          9        640: 10% ━─────────── 2/20 3.5it/s 0.4s<5.1s

       2/10      1.46G     0.7985      9.883   0.004384          8        640: 15% ━╸────────── 3/20 4.6it/s 0.6s<3.7s

       2/10      1.46G     0.7894      9.654   0.004144         10        640: 20% ━━────────── 4/20 5.4it/s 0.7s<3.0s

       2/10      1.46G     0.8603      9.832   0.004461          8        640: 25% ━━━───────── 5/20 5.9it/s 0.9s<2.6s

       2/10      1.46G     0.8978      9.872   0.004496          8        640: 30% ━━━╸──────── 6/20 6.5it/s 1.0s<2.2s

       2/10      1.46G     0.8789      9.825   0.004412          8        640: 35% ━━━━──────── 7/20 6.5it/s 1.1s<2.0s

       2/10      1.46G     0.9143      9.881   0.004558          8        640: 40% ━━━━╸─────── 8/20 6.4it/s 1.3s<1.9s

       2/10      1.46G      0.923      9.888    0.00468          8        640: 45% ━━━━━─────── 9/20 6.2it/s 1.5s<1.8s

       2/10      1.46G     0.9291      9.847   0.004726          8        640: 50% ━━━━━━────── 10/20 6.8it/s 1.6s<1.5s

       2/10      1.46G      0.933      9.802   0.004729          8        640: 55% ━━━━━━╸───── 11/20 6.7it/s 1.7s<1.4s

       2/10      1.46G      0.936      9.776   0.004809          8        640: 60% ━━━━━━━───── 12/20 7.1it/s 1.9s<1.1s

       2/10      1.46G     0.9256      9.744   0.004728          8        640: 65% ━━━━━━━╸──── 13/20 7.3it/s 2.0s<1.0s

       2/10      1.46G     0.9159      9.721   0.004603          8        640: 70% ━━━━━━━━──── 14/20 7.1it/s 2.1s<0.8s

       2/10      1.46G      0.912      9.682   0.004621          8        640: 75% ━━━━━━━━━─── 15/20 7.2it/s 2.3s<0.7s

       2/10      1.46G     0.9133      9.614   0.004558          9        640: 80% ━━━━━━━━━╸── 16/20 7.7it/s 2.4s<0.5s

       2/10      1.46G     0.9172      9.608   0.004595          8        640: 85% ━━━━━━━━━━── 17/20 7.5it/s 2.5s<0.4s

       2/10      1.46G     0.9286      9.603   0.004696          8        640: 90% ━━━━━━━━━━╸─ 18/20 7.3it/s 2.7s<0.3s

       2/10      1.46G     0.9268      9.608   0.004808          8        640: 95% ━━━━━━━━━━━─ 19/20 7.1it/s 2.8s<0.1s

       2/10      1.46G     0.9268      9.608   0.004808          8        640: 100% ━━━━━━━━━━━━ 20/20 7.1it/s 2.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 3.3it/s 0.2s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 12.3it/s 0.2s

                   all         40         43    0.00292      0.814      0.249      0.155

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       3/10      1.46G      1.045      9.417   0.005114          8        640: 0% ──────────── 0/20  0.2s

       3/10      1.46G      1.082      9.355   0.005447          8        640: 5% ╸─────────── 1/20 2.0it/s 0.3s<9.3s

       3/10      1.46G      1.054      9.288    0.00543          8        640: 10% ━─────────── 2/20 3.7it/s 0.4s<4.8s

       3/10      1.46G      1.009      9.168   0.005662          8        640: 15% ━╸────────── 3/20 5.1it/s 0.6s<3.3s

       3/10      1.46G      1.004      9.239   0.005989          8        640: 20% ━━────────── 4/20 5.5it/s 0.7s<2.9s

       3/10      1.46G      1.006      9.126   0.005686          9        640: 25% ━━━───────── 5/20 5.7it/s 0.9s<2.6s

       3/10      1.46G     0.9631      9.061   0.005413          8        640: 30% ━━━╸──────── 6/20 6.2it/s 1.0s<2.2s

       3/10      1.46G     0.9987       9.09    0.00582          8        640: 35% ━━━━──────── 7/20 6.8it/s 1.1s<1.9s

       3/10      1.46G      1.048      9.184   0.006063          8        640: 40% ━━━━╸─────── 8/20 6.9it/s 1.3s<1.7s

       3/10      1.46G      1.067      9.216   0.006117          8        640: 45% ━━━━━─────── 9/20 7.1it/s 1.4s<1.5s

       3/10      1.46G      1.112      9.351   0.006332          8        640: 50% ━━━━━━────── 10/20 6.8it/s 1.6s<1.5s

       3/10      1.46G      1.129      9.348    0.00638          8        640: 55% ━━━━━━╸───── 11/20 7.0it/s 1.7s<1.3s

       3/10      1.46G      1.144      9.351   0.006624          8        640: 60% ━━━━━━━───── 12/20 7.1it/s 1.8s<1.1s

       3/10      1.46G      1.174      9.348   0.006716          8        640: 65% ━━━━━━━╸──── 13/20 6.8it/s 2.0s<1.0s

       3/10      1.46G      1.158      9.313   0.006583          8        640: 70% ━━━━━━━━──── 14/20 6.9it/s 2.1s<0.9s

       3/10      1.46G      1.136      9.338   0.006443          7        640: 75% ━━━━━━━━━─── 15/20 7.1it/s 2.3s<0.7s

       3/10      1.46G      1.134      9.243   0.006321         10        640: 80% ━━━━━━━━━╸── 16/20 7.1it/s 2.4s<0.6s

       3/10      1.46G      1.141       9.24   0.006434          8        640: 85% ━━━━━━━━━━── 17/20 7.3it/s 2.5s<0.4s

       3/10      1.46G      1.124      9.187   0.006268          8        640: 90% ━━━━━━━━━━╸─ 18/20 7.4it/s 2.7s<0.3s

       3/10      1.46G      1.123      9.166   0.006322          8        640: 95% ━━━━━━━━━━━─ 19/20 7.3it/s 2.8s<0.1s

       3/10      1.46G      1.123      9.166   0.006322          8        640: 100% ━━━━━━━━━━━━ 20/20 7.1it/s 2.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 3.6it/s 0.2s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 12.6it/s 0.2s

                   all         40         43    0.00258      0.721      0.125     0.0554

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       4/10      1.46G      1.073      8.273   0.004193          9        640: 0% ──────────── 0/20  0.1s

       4/10      1.46G      1.088      8.695   0.004929          8        640: 5% ╸─────────── 1/20 1.9it/s 0.3s<10.3s

       4/10      1.46G       1.17      8.469   0.004715         10        640: 10% ━─────────── 2/20 3.6it/s 0.4s<5.0s

       4/10      1.46G      1.247      8.616    0.00545          8        640: 15% ━╸────────── 3/20 4.5it/s 0.6s<3.8s

       4/10      1.46G      1.226      8.624   0.005455          8        640: 20% ━━────────── 4/20 5.5it/s 0.7s<2.9s

       4/10      1.46G      1.176       8.61   0.005739          8        640: 25% ━━━───────── 5/20 6.1it/s 0.8s<2.5s

       4/10      1.46G      1.191      8.641   0.005969          8        640: 30% ━━━╸──────── 6/20 6.1it/s 1.0s<2.3s

       4/10      1.46G      1.154      8.622   0.006098          8        640: 35% ━━━━──────── 7/20 6.6it/s 1.1s<2.0s

       4/10      1.46G      1.174      8.609   0.006386          8        640: 40% ━━━━╸─────── 8/20 7.2it/s 1.2s<1.7s

       4/10      1.46G      1.194      8.626   0.006824          8        640: 45% ━━━━━─────── 9/20 6.7it/s 1.4s<1.6s

       4/10      1.46G      1.168      8.552   0.006905          8        640: 50% ━━━━━━────── 10/20 6.9it/s 1.5s<1.4s

       4/10      1.46G      1.148      8.464   0.006808          8        640: 55% ━━━━━━╸───── 11/20 7.2it/s 1.7s<1.3s

       4/10      1.46G      1.176      8.491   0.006987          8        640: 60% ━━━━━━━───── 12/20 7.6it/s 1.8s<1.1s

       4/10      1.46G      1.203      8.506   0.007321          8        640: 65% ━━━━━━━╸──── 13/20 7.1it/s 2.0s<1.0s

       4/10      1.46G      1.193      8.479   0.007189          8        640: 70% ━━━━━━━━──── 14/20 7.1it/s 2.1s<0.8s

       4/10      1.46G      1.211      8.478   0.007262          8        640: 75% ━━━━━━━━━─── 15/20 7.3it/s 2.2s<0.7s

       4/10      1.46G      1.208      8.468   0.007247          8        640: 80% ━━━━━━━━━╸── 16/20 7.3it/s 2.4s<0.6s

       4/10      1.46G      1.222      8.475   0.007256          8        640: 85% ━━━━━━━━━━── 17/20 7.3it/s 2.5s<0.4s

       4/10      1.46G      1.216      8.454   0.007208          8        640: 90% ━━━━━━━━━━╸─ 18/20 7.7it/s 2.6s<0.3s

       4/10      1.46G      1.213      8.404     0.0071          9        640: 95% ━━━━━━━━━━━─ 19/20 7.9it/s 2.7s<0.1s

       4/10      1.46G      1.213      8.404     0.0071          9        640: 100% ━━━━━━━━━━━━ 20/20 7.3it/s 2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 3.8it/s 0.2s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 13.9it/s 0.2s

                   all         40         43      0.896      0.201      0.458      0.311

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       5/10      1.46G      1.038      8.031   0.005057          8        640: 0% ──────────── 0/20  0.1s

       5/10      1.46G      1.051      7.943   0.005721          8        640: 5% ╸─────────── 1/20 2.5it/s 0.2s<7.7s

       5/10      1.46G      1.003      7.825   0.005641          8        640: 10% ━─────────── 2/20 3.9it/s 0.4s<4.7s

       5/10      1.46G      1.037        7.9   0.006015          8        640: 15% ━╸────────── 3/20 4.8it/s 0.5s<3.6s

       5/10      1.46G      1.092      7.847   0.006106          9        640: 20% ━━────────── 4/20 5.6it/s 0.7s<2.9s

       5/10      1.46G      1.101      7.852   0.006558          8        640: 25% ━━━───────── 5/20 5.8it/s 0.8s<2.6s

       5/10      1.46G      1.082      7.777   0.006499          8        640: 30% ━━━╸──────── 6/20 6.8it/s 0.9s<2.1s

       5/10      1.46G      1.049      7.696   0.006356          8        640: 35% ━━━━──────── 7/20 7.0it/s 1.1s<1.9s

       5/10      1.46G      1.045      7.545   0.006315         10        640: 40% ━━━━╸─────── 8/20 6.8it/s 1.2s<1.8s

       5/10      1.46G      1.029      7.529   0.006211          8        640: 45% ━━━━━─────── 9/20 6.9it/s 1.4s<1.6s

       5/10      1.46G      1.017      7.521    0.00627          8        640: 50% ━━━━━━────── 10/20 7.3it/s 1.5s<1.4s

       5/10      1.46G      1.014      7.531   0.006243          8        640: 55% ━━━━━━╸───── 11/20 7.3it/s 1.6s<1.2s

       5/10      1.46G      1.022      7.536    0.00628          8        640: 60% ━━━━━━━───── 12/20 7.1it/s 1.8s<1.1s

       5/10      1.46G      1.018      7.543   0.006294          8        640: 65% ━━━━━━━╸──── 13/20 7.1it/s 1.9s<1.0s

       5/10      1.46G       1.01      7.524   0.006243          8        640: 70% ━━━━━━━━──── 14/20 7.3it/s 2.0s<0.8s

       5/10      1.46G      1.031      7.529   0.006351          8        640: 75% ━━━━━━━━━─── 15/20 7.0it/s 2.2s<0.7s

       5/10      1.46G      1.053      7.555   0.006485          8        640: 80% ━━━━━━━━━╸── 16/20 7.0it/s 2.3s<0.6s

       5/10      1.46G      1.052      7.543   0.006521          8        640: 85% ━━━━━━━━━━── 17/20 7.0it/s 2.5s<0.4s

       5/10      1.46G      1.056      7.512   0.006371          9        640: 90% ━━━━━━━━━━╸─ 18/20 7.1it/s 2.6s<0.3s

       5/10      1.46G      1.052      7.483   0.006338          8        640: 95% ━━━━━━━━━━━─ 19/20 7.2it/s 2.7s<0.1s

       5/10      1.46G      1.052      7.483   0.006338          8        640: 100% ━━━━━━━━━━━━ 20/20 7.3it/s 2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 3.3it/s 0.2s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 11.3it/s 0.3s

                   all         40         43      0.569      0.395      0.476       0.37

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       6/10      1.46G       1.05      7.318   0.005534          8        640: 0% ──────────── 0/20  0.1s

       6/10      1.46G      0.948      7.185   0.005154          8        640: 5% ╸─────────── 1/20 1.6it/s 0.3s<11.7s

       6/10      1.46G      1.062      7.379   0.006668          8        640: 10% ━─────────── 2/20 3.1it/s 0.5s<5.9s

       6/10      1.46G      1.086      7.432   0.006315          8        640: 15% ━╸────────── 3/20 4.6it/s 0.6s<3.7s

       6/10      1.46G      1.083      7.178   0.006048         10        640: 20% ━━────────── 4/20 5.7it/s 0.7s<2.8s

       6/10      1.46G      1.076      7.181   0.005898          8        640: 25% ━━━───────── 5/20 6.2it/s 0.8s<2.4s

       6/10      1.46G      1.095      7.255   0.005665          8        640: 30% ━━━╸──────── 6/20 6.4it/s 1.0s<2.2s

       6/10      1.46G      1.127      7.328   0.005642          8        640: 35% ━━━━──────── 7/20 6.8it/s 1.1s<1.9s

       6/10      1.46G      1.093      7.304   0.005847          8        640: 40% ━━━━╸─────── 8/20 6.5it/s 1.3s<1.8s

       6/10      1.46G      1.092      7.272   0.005835          8        640: 45% ━━━━━─────── 9/20 6.7it/s 1.4s<1.6s

       6/10      1.46G      1.088      7.247   0.005885          8        640: 50% ━━━━━━────── 10/20 6.9it/s 1.6s<1.4s

       6/10      1.46G      1.066      7.217   0.005917          8        640: 55% ━━━━━━╸───── 11/20 7.0it/s 1.7s<1.3s

       6/10      1.46G      1.076      7.179   0.006044          9        640: 60% ━━━━━━━───── 12/20 7.3it/s 1.8s<1.1s

       6/10      1.46G      1.092      7.231   0.006203          8        640: 65% ━━━━━━━╸──── 13/20 7.3it/s 1.9s<1.0s

       6/10      1.46G      1.091      7.225   0.006261          8        640: 70% ━━━━━━━━──── 14/20 7.5it/s 2.1s<0.8s

       6/10      1.46G      1.086      7.211   0.006258          8        640: 75% ━━━━━━━━━─── 15/20 7.2it/s 2.2s<0.7s

       6/10      1.46G      1.077      7.196   0.006216          8        640: 80% ━━━━━━━━━╸── 16/20 7.2it/s 2.4s<0.6s

       6/10      1.46G      1.071      7.178   0.006086          8        640: 85% ━━━━━━━━━━── 17/20 7.0it/s 2.5s<0.4s

       6/10      1.46G      1.073      7.193   0.006011          8        640: 90% ━━━━━━━━━━╸─ 18/20 6.9it/s 2.7s<0.3s

       6/10      1.46G      1.064      7.174   0.006061          8        640: 95% ━━━━━━━━━━━─ 19/20 6.6it/s 2.8s<0.2s

       6/10      1.46G      1.064      7.174   0.006061          8        640: 100% ━━━━━━━━━━━━ 20/20 7.0it/s 2.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 3.8it/s 0.2s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 13.6it/s 0.2s

                   all         40         43      0.554      0.558      0.541      0.414

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       7/10      1.46G      1.031      6.312   0.004415         10        640: 0% ──────────── 0/20  0.1s

       7/10      1.46G      1.009      6.274   0.005185          9        640: 5% ╸─────────── 1/20 2.0it/s 0.3s<9.7s

       7/10      1.46G      1.112      6.389   0.005459          9        640: 10% ━─────────── 2/20 3.7it/s 0.4s<4.9s

       7/10      1.46G      1.055      6.484   0.005665          8        640: 15% ━╸────────── 3/20 4.5it/s 0.6s<3.8s

       7/10      1.46G      1.027      6.528   0.005615          8        640: 20% ━━────────── 4/20 5.0it/s 0.7s<3.2s

       7/10      1.46G      1.024      6.578   0.005883          8        640: 25% ━━━───────── 5/20 5.5it/s 0.9s<2.7s

       7/10      1.46G       1.07      6.652   0.006258          8        640: 30% ━━━╸──────── 6/20 5.8it/s 1.0s<2.4s

       7/10      1.46G      1.039       6.72   0.005926          8        640: 35% ━━━━──────── 7/20 6.2it/s 1.2s<2.1s

       7/10      1.46G      1.024      6.712   0.006039          8        640: 40% ━━━━╸─────── 8/20 6.7it/s 1.3s<1.8s

       7/10      1.46G      1.013        6.7   0.005841          8        640: 45% ━━━━━─────── 9/20 6.8it/s 1.4s<1.6s

       7/10      1.46G      1.025      6.724   0.006067          8        640: 50% ━━━━━━────── 10/20 6.8it/s 1.6s<1.5s

       7/10      1.46G       1.05      6.783   0.006096          8        640: 55% ━━━━━━╸───── 11/20 7.2it/s 1.7s<1.2s

       7/10      1.46G      1.044      6.772   0.005994          8        640: 60% ━━━━━━━───── 12/20 7.3it/s 1.8s<1.1s

       7/10      1.46G       1.02      6.751   0.005975          8        640: 65% ━━━━━━━╸──── 13/20 7.2it/s 2.0s<1.0s

       7/10      1.46G      1.018      6.732   0.005849          8        640: 70% ━━━━━━━━──── 14/20 7.3it/s 2.1s<0.8s

       7/10      1.46G       1.02      6.722   0.005872          8        640: 75% ━━━━━━━━━─── 15/20 7.5it/s 2.2s<0.7s

       7/10      1.46G      1.021      6.714    0.00575          8        640: 80% ━━━━━━━━━╸── 16/20 7.4it/s 2.4s<0.5s

       7/10      1.46G       1.01      6.701   0.005761          8        640: 85% ━━━━━━━━━━── 17/20 7.3it/s 2.5s<0.4s

       7/10      1.46G      1.011        6.7   0.005661          8        640: 90% ━━━━━━━━━━╸─ 18/20 7.3it/s 2.6s<0.3s

       7/10      1.46G      1.004      6.684   0.005602          8        640: 95% ━━━━━━━━━━━─ 19/20 7.0it/s 2.8s<0.1s

       7/10      1.46G      1.004      6.684   0.005602          8        640: 100% ━━━━━━━━━━━━ 20/20 7.1it/s 2.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 3.7it/s 0.2s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 13.5it/s 0.2s

                   all         40         43      0.596      0.653      0.608      0.467

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       8/10      1.46G      1.061      7.083   0.006911          8        640: 0% ──────────── 0/20  0.1s

       8/10      1.46G     0.9449      6.861   0.005303          8        640: 5% ╸─────────── 1/20 1.9it/s 0.3s<9.8s

       8/10      1.46G     0.9197      6.833    0.00474          8        640: 10% ━─────────── 2/20 3.4it/s 0.4s<5.3s

       8/10      1.46G     0.8509      6.706   0.004568          8        640: 15% ━╸────────── 3/20 4.4it/s 0.6s<3.8s

       8/10      1.46G     0.8649      6.642    0.00466          8        640: 20% ━━────────── 4/20 5.7it/s 0.7s<2.8s

       8/10      1.46G     0.8797      6.654   0.004744          8        640: 25% ━━━───────── 5/20 6.0it/s 0.8s<2.5s

       8/10      1.46G     0.8972       6.69   0.004999          8        640: 30% ━━━╸──────── 6/20 6.4it/s 1.0s<2.2s

       8/10      1.46G     0.9146      6.683   0.005018          8        640: 35% ━━━━──────── 7/20 6.5it/s 1.1s<2.0s

       8/10      1.46G     0.9046      6.639   0.004814          8        640: 40% ━━━━╸─────── 8/20 6.6it/s 1.3s<1.8s

       8/10      1.46G     0.9223      6.519   0.004823         10        640: 45% ━━━━━─────── 9/20 6.6it/s 1.4s<1.7s

       8/10      1.46G     0.9436      6.532   0.005009          8        640: 50% ━━━━━━────── 10/20 7.4it/s 1.5s<1.4s

       8/10      1.46G     0.9502      6.557   0.004999          8        640: 55% ━━━━━━╸───── 11/20 7.3it/s 1.7s<1.2s

       8/10      1.46G     0.9626       6.56   0.004996          8        640: 60% ━━━━━━━───── 12/20 7.1it/s 1.8s<1.1s

       8/10      1.46G     0.9766      6.589   0.005183          8        640: 65% ━━━━━━━╸──── 13/20 6.9it/s 2.0s<1.0s

       8/10      1.46G     0.9737       6.58   0.005245          8        640: 70% ━━━━━━━━──── 14/20 6.9it/s 2.1s<0.9s

       8/10      1.46G     0.9632      6.539   0.005279          9        640: 75% ━━━━━━━━━─── 15/20 7.1it/s 2.3s<0.7s

       8/10      1.46G     0.9715      6.497   0.005281          9        640: 80% ━━━━━━━━━╸── 16/20 7.4it/s 2.4s<0.5s

       8/10      1.46G     0.9698      6.493   0.005286          8        640: 85% ━━━━━━━━━━── 17/20 7.4it/s 2.5s<0.4s

       8/10      1.46G     0.9785      6.504   0.005398          8        640: 90% ━━━━━━━━━━╸─ 18/20 7.2it/s 2.7s<0.3s

       8/10      1.46G     0.9754        6.5    0.00539          8        640: 95% ━━━━━━━━━━━─ 19/20 7.1it/s 2.8s<0.1s

       8/10      1.46G     0.9754        6.5    0.00539          8        640: 100% ━━━━━━━━━━━━ 20/20 7.1it/s 2.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 3.2it/s 0.2s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 11.5it/s 0.3s

                   all         40         43      0.497      0.651      0.627      0.471

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

       9/10      1.46G     0.8046      6.169   0.003719          8        640: 0% ──────────── 0/20  0.1s

       9/10      1.46G     0.8213      5.902   0.003961          9        640: 5% ╸─────────── 1/20 2.1it/s 0.3s<9.2s

       9/10      1.46G     0.8642      5.915   0.004343          9        640: 10% ━─────────── 2/20 3.4it/s 0.4s<5.4s

       9/10      1.46G     0.8735      5.964   0.004762          8        640: 15% ━╸────────── 3/20 4.7it/s 0.5s<3.6s

       9/10      1.46G     0.9765      6.129   0.004986          8        640: 20% ━━────────── 4/20 5.4it/s 0.7s<2.9s

       9/10      1.46G      0.985      6.149    0.00519          8        640: 25% ━━━───────── 5/20 5.8it/s 0.8s<2.6s

       9/10      1.46G     0.9737      6.213   0.005451          8        640: 30% ━━━╸──────── 6/20 6.7it/s 0.9s<2.1s

       9/10      1.46G     0.9793      6.226   0.005603          8        640: 35% ━━━━──────── 7/20 6.8it/s 1.1s<1.9s

       9/10      1.46G     0.9506       6.23    0.00551          8        640: 40% ━━━━╸─────── 8/20 6.9it/s 1.2s<1.7s

       9/10      1.46G     0.9369      6.214   0.005389          8        640: 45% ━━━━━─────── 9/20 6.9it/s 1.4s<1.6s

       9/10      1.46G      0.937      6.243   0.005335          8        640: 50% ━━━━━━────── 10/20 6.9it/s 1.5s<1.4s

       9/10      1.46G     0.9445      6.241   0.005428          8        640: 55% ━━━━━━╸───── 11/20 7.1it/s 1.7s<1.3s

       9/10      1.46G     0.9595      6.213   0.005403         10        640: 60% ━━━━━━━───── 12/20 7.4it/s 1.8s<1.1s

       9/10      1.46G     0.9519      6.222   0.005475          8        640: 65% ━━━━━━━╸──── 13/20 7.2it/s 1.9s<1.0s

       9/10      1.46G     0.9554      6.215   0.005491          8        640: 70% ━━━━━━━━──── 14/20 7.7it/s 2.0s<0.8s

       9/10      1.46G     0.9386      6.206   0.005413          8        640: 75% ━━━━━━━━━─── 15/20 7.5it/s 2.2s<0.7s

       9/10      1.46G     0.9362      6.217   0.005311          8        640: 80% ━━━━━━━━━╸── 16/20 7.3it/s 2.3s<0.5s

       9/10      1.46G     0.9247       6.19   0.005265          8        640: 85% ━━━━━━━━━━── 17/20 6.8it/s 2.5s<0.4s

       9/10      1.46G     0.9096      6.198   0.005198          8        640: 90% ━━━━━━━━━━╸─ 18/20 7.0it/s 2.6s<0.3s

       9/10      1.46G     0.9043      6.203   0.005108          8        640: 95% ━━━━━━━━━━━─ 19/20 7.0it/s 2.8s<0.1s

       9/10      1.46G     0.9043      6.203   0.005108          8        640: 100% ━━━━━━━━━━━━ 20/20 7.2it/s 2.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 3.7it/s 0.2s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 13.6it/s 0.2s

                   all         40         43      0.542      0.698      0.656      0.513

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

      10/10      1.46G     0.7862      6.163    0.00522          8        640: 0% ──────────── 0/20  0.1s

      10/10      1.46G      0.757      6.205   0.005336          8        640: 5% ╸─────────── 1/20 2.0it/s 0.3s<9.3s

      10/10      1.46G     0.7607      6.256   0.004711          8        640: 10% ━─────────── 2/20 3.7it/s 0.4s<4.9s

      10/10      1.46G      0.771      6.115   0.004307          9        640: 15% ━╸────────── 3/20 4.4it/s 0.6s<3.9s

      10/10      1.46G     0.8614      6.181   0.004742          8        640: 20% ━━────────── 4/20 5.2it/s 0.7s<3.1s

      10/10      1.46G     0.8777       6.22   0.004825          8        640: 25% ━━━───────── 5/20 6.0it/s 0.8s<2.5s

      10/10      1.46G     0.8735       6.22   0.004749          8        640: 30% ━━━╸──────── 6/20 6.5it/s 1.0s<2.2s

      10/10      1.46G     0.8961      6.267    0.00471          8        640: 35% ━━━━──────── 7/20 6.7it/s 1.1s<1.9s

      10/10      1.46G     0.9101      6.281   0.004629          8        640: 40% ━━━━╸─────── 8/20 6.9it/s 1.2s<1.7s

      10/10      1.46G     0.8896      6.258   0.004505          8        640: 45% ━━━━━─────── 9/20 7.0it/s 1.4s<1.6s

      10/10      1.46G     0.8892      6.229    0.00454          8        640: 50% ━━━━━━────── 10/20 7.4it/s 1.5s<1.3s

      10/10      1.46G     0.8894      6.214   0.004643          8        640: 55% ━━━━━━╸───── 11/20 7.1it/s 1.6s<1.3s

      10/10      1.46G     0.8891      6.198   0.004706          8        640: 60% ━━━━━━━───── 12/20 7.2it/s 1.8s<1.1s

      10/10      1.46G     0.9052      6.153   0.004748         10        640: 65% ━━━━━━━╸──── 13/20 7.3it/s 1.9s<1.0s

      10/10      1.46G     0.9371      6.202   0.004831          8        640: 70% ━━━━━━━━──── 14/20 7.3it/s 2.1s<0.8s

      10/10      1.46G      0.929       6.18   0.004815          8        640: 75% ━━━━━━━━━─── 15/20 7.2it/s 2.2s<0.7s

      10/10      1.46G     0.9332      6.174   0.004822          8        640: 80% ━━━━━━━━━╸── 16/20 7.0it/s 2.3s<0.6s

      10/10      1.46G     0.9284      6.178   0.004792          8        640: 85% ━━━━━━━━━━── 17/20 6.8it/s 2.5s<0.4s

      10/10      1.46G      0.937      6.199   0.004847          8        640: 90% ━━━━━━━━━━╸─ 18/20 7.3it/s 2.6s<0.3s

      10/10      1.46G      0.949      6.218   0.004932          8        640: 95% ━━━━━━━━━━━─ 19/20 7.7it/s 2.7s<0.1s

      10/10      1.46G      0.949      6.218   0.004932          8        640: 100% ━━━━━━━━━━━━ 20/20 7.3it/s 2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 3.2it/s 0.2s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 12.3it/s 0.2s

                   all         40         43      0.632      0.674       0.68      0.545

10 epochs completed in 0.014 hours.

Optimizer stripped from /home/sagemaker-user/sagemaker-yolo/runs/gpu-160img-640px-10epochs/weights/last.pt, 5.4MB

Optimizer stripped from /home/sagemaker-user/sagemaker-yolo/runs/gpu-160img-640px-10epochs/weights/best.pt, 5.4MB

Validating /home/sagemaker-user/sagemaker-yolo/runs/gpu-160img-640px-10epochs/weights/best.pt...

Ultralytics 8.4.120 🚀 Python-3.12.13 torch-2.13.0+cu130 CUDA:0 (Tesla T4, 14913MiB)

YOLO26n summary (fused): 122 layers, 2,375,031 parameters, 0 gradients, 5.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 66% ━━━━━━━━──── 2/3 2.5it/s 0.2s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.4it/s 0.4s

                   all         40         43      0.633      0.674      0.681      0.548

Speed: 0.2ms preprocess, 2.7ms inference, 0.0ms loss, 0.2ms postprocess per image

Results saved to /home/sagemaker-user/sagemaker-yolo/runs/gpu-160img-640px-10epochs

MLflow: results logged to arn:aws:sagemaker:ca-central-1:099139718958:mlflow-tracking-server/sagemaker-yolo-dev
MLflow: disable with 'yolo settings mlflow=False'

MLflow: mlflow run still alive, remember to close it using mlflow.end_run()

🏃 View run gpu-160img-640px-10epochs at: https://ca-central-1.experiments.sagemaker.aws/#/experiments/3/runs/8843e42655bc431bbf79df04b2f08e0b
🧪 View experiment at: https://ca-central-1.experiments.sagemaker.aws/#/experiments/3
[1/1] done in 63s

🏃 View run gpu-160img-640px-10epochs at: https://ca-central-1.experiments.sagemaker.aws/#/experiments/3/runs/8843e42655bc431bbf79df04b2f08e0b
🧪 View experiment at: https://ca-central-1.experiments.sagemaker.aws/#/experiments/3

,name,run_id,save_dir,epochs,mAP50,mAP50-95,elapsed_s,pass,instance
0,cpu-160img-640px-10epochs,5919ce8856b74698b1ebba0b9339ba47,/home/sagemaker-user/sagemaker-yolo/runs/cpu-1...,10,0.779561,0.611877,613,cpu,ml.g4dn.xlarge
1,gpu-160img-640px-10epochs,8843e42655bc431bbf79df04b2f08e0b,/home/sagemaker-user/sagemaker-yolo/runs/gpu-1...,10,0.680899,0.547945,63,gpu,ml.g4dn.xlarge

## Compare

Read both passes back from MLflow.

In [7]:
runs = mlflow.search_runs(experiment_ids=[experiment.experiment_id])

if runs.empty:
    raise RuntimeError("no runs in the experiment yet")

# elapsed_seconds is logged by run_sweep; tags.pass by the cell above
table = pd.DataFrame({
    "run": runs["tags.mlflow.runName"],
    "pass": runs.get("tags.pass"),
    "instance": runs.get("tags.instance"),
    "start": runs["start_time"],
    "epochs": pd.to_numeric(runs.get("params.epochs"), errors="coerce"),
    "images": pd.to_numeric(runs.get("params.data.total_images"), errors="coerce"),
    "seconds": pd.to_numeric(runs.get("metrics.elapsed_seconds"), errors="coerce"),
    "mAP50-95": pd.to_numeric(runs.get("metrics.metrics/mAP50-95B"), errors="coerce"),
}).dropna(subset=["seconds", "pass"])

before = len(table)
table = table.sort_values("start", ascending=False).drop_duplicates(
    subset=["pass", "epochs", "images"], keep="first"
)
if before != len(table):
    print(f"dropped {before - len(table)} superseded run(s) from earlier sessions")

have = set(table["pass"].unique())
print("passes on the server:", sorted(have))

for label, subset in table.groupby("pass"):
    print(f"  {label:4} {len(subset)} runs on {sorted(set(subset['instance'].dropna()))}")

if {"cpu", "gpu"} - have:
    print(
        f"\nMissing the {sorted({'cpu', 'gpu'} - have)[0]} pass — "
        "the comparison below stays empty until both exist."
    )

table.sort_values(["epochs", "pass"])

dropped 9 superseded run(s) from earlier sessions
passes on the server: ['cpu', 'gpu']
  cpu  2 runs on ['ml.g4dn.xlarge']
  gpu  2 runs on ['ml.g4dn.xlarge']

,run,pass,instance,start,epochs,images,seconds,mAP50-95
1,cpu-160img-640px-10epochs,cpu,ml.g4dn.xlarge,2026-08-14 00:17:05.185000+00:00,10,200,612.662261,0.611877
0,gpu-160img-640px-10epochs,gpu,ml.g4dn.xlarge,2026-08-14 00:27:20.548000+00:00,10,200,62.791677,0.547945
4,cpu-160img-640px-20epochs,cpu,ml.g4dn.xlarge,2026-08-13 23:45:42.462000+00:00,20,200,1234.741550,0.759494
2,gpu-160img-640px-20epochs,gpu,ml.g4dn.xlarge,2026-08-14 00:07:24.795000+00:00,20,200,89.885746,0.798119

### Speedup

Matched on `epochs` and image count, so each row compares like with like.

In [8]:
BOTH = not ({"cpu", "gpu"} - have)

if not BOTH:
    print("need both passes before this can be computed")
else:
    cpu = table[table["pass"] == "cpu"].set_index(["epochs", "images"])
    gpu = table[table["pass"] == "gpu"].set_index(["epochs", "images"])

    speedup = pd.DataFrame({
        "cpu_min": (cpu["seconds"] / 60).round(1),
        "gpu_min": (gpu["seconds"] / 60).round(1),
        "cpu_mAP": cpu["mAP50-95"].round(4),
        "gpu_mAP": gpu["mAP50-95"].round(4),
    }).dropna()

    speedup["speedup"] = (speedup["cpu_min"] / speedup["gpu_min"]).round(1)
    speedup["mAP_delta"] = (speedup["gpu_mAP"] - speedup["cpu_mAP"]).round(4)

    display(speedup.reset_index())

    print(f"\nmedian speedup {speedup['speedup'].median():.1f}x")
    # different kernels and reduction orders, so exact parity is not expected
    print(f"largest mAP gap {speedup['mAP_delta'].abs().max():.4f}"
          " (small values confirm the two devices agree)")

   epochs  images  cpu_min  gpu_min  cpu_mAP  gpu_mAP  speedup  mAP_delta
0      10     200     10.2      1.0   0.6119   0.5479     10.2    -0.0640
1      20     200     20.6      1.5   0.7595   0.7981     13.7     0.0386

median speedup 11.9x
largest mAP gap 0.0640 (small values confirm the two devices agree)

Wall-clock per config.

In [ ]:
%matplotlib inline

if not BOTH:
    print("need both passes before this can be plotted")
else:
    fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))

    pivot = table.pivot_table(index="epochs", columns="pass", values="seconds") / 60
    pivot.plot(kind="bar", ax=axes[0], color={"cpu": "#888", "gpu": "#2a9d8f"})
    axes[0].set_ylabel("minutes")
    axes[0].set_xlabel("epochs")
    axes[0].set_title("wall-clock")
    axes[0].grid(alpha=0.3, axis="y")
    axes[0].tick_params(axis="x", rotation=0)

    acc = table.pivot_table(index="epochs", columns="pass", values="mAP50-95")
    acc.plot(kind="bar", ax=axes[1], color={"cpu": "#888", "gpu": "#2a9d8f"})
    axes[1].set_ylabel("mAP50-95")
    axes[1].set_xlabel("epochs")
    axes[1].set_title("accuracy (should match closely)")
    axes[1].set_ylim(0, 1)
    axes[1].grid(alpha=0.3, axis="y")
    axes[1].tick_params(axis="x", rotation=0)

    plt.tight_layout()
    plt.show()

### Cost

In [ ]:
# USD per hour, on-demand. Update for your region before relying on this.
RATES = {
    "ml.t3.xlarge": 0.223,
    "ml.g4dn.xlarge": 0.818,
}

if not BOTH:
    print("need both passes before this can be computed")
else:
    cost = table.copy()
    cost["rate"] = cost["instance"].map(RATES)
    unpriced = sorted(set(cost.loc[cost["rate"].isna(), "instance"].dropna()))

    if unpriced:
        print(f"no rate for {unpriced} — add them to RATES")

    cost["usd"] = (cost["seconds"] / 3600 * cost["rate"]).round(3)
    summary = cost.groupby("pass").agg(
        instance=("instance", "first"),
        rate_per_hour=("rate", "first"),
        total_min=("seconds", lambda s: round(s.sum() / 60, 1)),
        total_usd=("usd", "sum"),
    ).round(3)

    display(summary)

    if summary["total_usd"].notna().all() and len(summary) == 2:
        cheaper = summary["total_usd"].idxmin()
        ratio = summary["total_usd"].max() / summary["total_usd"].min()
        print(f"\n{cheaper} is {ratio:.1f}x cheaper for this sweep")